name: Build LaTeX PDF

on:
  pull_request:
    paths:
      - "**/*.tex"
      - "**/*.puml"
      - "**/*.bib"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: |
            project-brief.tex
            report.tex
            january-deliverable.tex
          working_directory: ./doc/

      - name: Upload January deliverable artifact
        uses: actions/upload-artifact@v4
        with:
          name: january-deliverable
          path: doc/january-deliverable.pdf
          if-no-files-found: error

      - name: Upload project brief artifact
        uses: actions/upload-artifact@v4
        with:
          name: project-brief
          path: doc/project-brief.pdf
          if-no-files-found: error

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: doc/report.pdf
          if-no-files-found: error
